spring:
  application:
    name: ssen-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ssen}
    username: ${DB_USERNAME:ssen}
    password: ${DB_PASSWORD:ssen}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug

app:
  jwt:
    secret: ${JWT_SECRET:change-me-to-a-long-random-string}

---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    clean-disabled: true
logging:
  level:
    root: info
